name: 'Dependabot JIRA Action'
description: 'Creates JIRA issues from dependabot alerts'
author: 'Sprout Tech LLC'
inputs:
  label:
    required: true
    description: 'JIRA issue labels'
    default: "dependabot"
  projectKey:
    required: true
    description: 'JIRA issue project key'
  issueType:
    required: true
    description: 'JIRA issue type'
    default: "Bug"
runs:
  using: 'node18'
  main: 'dist/index.js'
